-- Auto-generated by inference/scrape_rep_sources.py
-- Embedding column intentionally left NULL; Phase 3.3 fills it.

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues', 'Issues', 'issues
Issues Home
Broadband and Rural Connectivity
Second Amendment
Veteran Issues
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '9be35c04e761103726d007afbda94b6ddd8a272c66c7c685927632120cde7f12')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues/issue/?IssueID=14890', 'Armed Forces & National Security', 'issues
Armed Forces & National Security
Share on Facebook
Share on Twitter
Print this Page
Share by Email
As a former Navy Supply Officer and Aviation Logistics officer, I understand the multitude of challenges our men and women in uniform face each day on and off the battlefield.
Our great nation is undeniably indebted to the men and women who work and fight each day to ensure our country remains a beacon of democracy and freedom. However, we must acknowledge that our liberties and freedoms are constantly under attack and that we must always remain vigilant and prepared. China, Russia, Iran, and North Korea remain the greatest foreign threats to our national security on several fronts. Additionally, we must be prepared to face the threats closer to home and at our borders.
I am committed to ensuring our armed forces have the tools and resources they need to protect our nation from all the threats we face. I am also committed to ensuring the families of our uniformed men and women have access to proper support and resources required to endure the sacrifices their loved ones make each day.
Related News
Rep. Clyde Votes to Support Troops & De-Woke DOD
June 14, 2024
| Posted in Press Releases
Rep. Clyde’s Bill to Redesignate Houthis as FTO Passes House with Bipartisan Support
April 17, 2024
| Posted in Press Releases
Rep. Clyde’s Bill to Redesignate Houthis as FTO Advanced by Committee
February 8, 2024
| Posted in Press Releases
CLYDE: Support Israel Without Bankrupting America
February 6, 2024
| Posted in Press Releases
Rep. Clyde Addresses Northeast Georgian Troops Before Overseas Deployment
February 1, 2024
| Posted in Press Releases
All Related News »
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '4aac6df821e4c6095cae5dabe8d6b0c885e447b94c0e28d6b83ba04a74297677')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues/issue/?IssueID=14893', 'Broadband and Rural Connectivity', 'issues
Broadband and Rural Connectivity
Share on Facebook
Share on Twitter
Print this Page
Share by Email
In the last two decades, the growth and widespread use of the internet has fundamentally transformed the way in which we interact, work, and engage in education and hobbies. Like generations before us that saw widespread adoption of electricity and telephones, the Internet is now inextricably linked to our lives and has developed into essential infrastructure. The pandemic has made evident the breadth and width of the digital divide in our unserved and underserved rural communities. We desperately need to bridge this gap in order to help commerce thrive, help families communicate, and increase access to education.
I will work with my colleagues to remove regulatory barriers of entry for emerging wired and wireless broadband technologies and seek to improve the process for delivering broadband grant funding to our communities in the Ninth District and across Georgia. Additionally, I believe the Internet is infrastructure and we must ensure there is robust investment in rural broadband in any bipartisan infrastructure package developed by this Congress.
Related News
Rep. Clyde Secures Key Commitment for Northeast Georgia Broadband Expansion Project
April 29, 2026
| Posted in Press Releases
Rep. Clyde Introduces Legislation to Improve Rural Broadband Mapping for FCC Grant Funding
October 26, 2021
| Posted in Press Releases
All Related News »
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '13629c64d566e6072d75706de5740ee24a2a57992f08236d82499f326311a6ca')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues/issue/?IssueID=14896', 'Government Operations & Small Business', 'issues
Government Operations & Small Business
Share on Facebook
Share on Twitter
Print this Page
Share by Email
Small businesses are the primary drivers of economic activity in communities across the country, and as a small businessman by trade, I know that to be true in Georgia''s 9th Congressional District. When it comes to business operations and the government, I believe that government should work to support all businesses and entrepreneurs by guaranteeing level playing fields on which to operate and compete freely on. Unfortunately, the government tends to make doing business harder than it should be, which I can personally attest to when the federal government attempted to seize nearly $1 million from my company a few years back. While I successfully fought the government''s egregious overreach, there are unfortunately too many businesses that succumb to the bureaucratic red tape and threats from federal agents ultimately driving them out of business. That''s wrong and the government should never thwart and close businesses, it should instead enable and support them.
That''s why I plan to look for opportunities in Congress to right-size the federal government and re-align its operations within the bounds of the U.S. Constitution, as was intended by our nation''s Founding Fathers. As a member of the House Committee on Oversight and Reform, I will have a front row seat to examine the federal government''s footprint to root out fraud, waste, and abuse. I wholeheartedly believe the government should work for the people, not against the people, and I am committed to ensuring just that while serving in Congress.
Related News
Rep. Clyde Demands Audit & Investigation of USPS Mail Delays
April 4, 2024
| Posted in Press Releases
Rep. Clyde Opposes USPS Reversal on Green Street Post Office Relocation
November 29, 2023
| Posted in Press Releases
Rep. Clyde Rejects Democrats'' Radical and Reckless Spending Package
March 10, 2022
| Posted in Press Releases
All Related News »
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', 'a1db8a083e1ae8968d184e5ec52ec0def280ee89497089b210e0239acdcd4471')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues/issue/?IssueID=14892', 'Protecting Life', 'issues
Protecting Life
Share on Facebook
Share on Twitter
Print this Page
Share by Email
At a time when so many leaders are pushing anti-life policies, it is more important than ever that we take a stand for our nation’s innocent unborn. As I build out my pro-life agenda, I have developed two leading principles on which I will never waver when it comes to protecting life.
First and foremost, I believe that not one taxpayer dollar should be allowed to fund abortion programs and services. The Hyde Amendment – a provision that blocks federal funds from being used for abortions – and other similar provisions are under attack as Democrats push their radical agenda. I am committed to opposing all legislation that weakens these long-standing bipartisan provisions.
Secondly, I believe that life begins at the moment of conception, and thus, abortions should be abolished entirely, except in the rare instances when the life of the mother is at risk. I recognize that our progress towards this goal will be slow and difficult, but I am committed to doing everything in my capacity as a member of Congress to protect the sanctity of life. Remember, our Declaration of Independence boldly proclaims, "We hold these truths to be self-evident... life, liberty and the pursuit of happiness. The first unalienable right stated was life.
Related News
Rep. Clyde Leads House GOP Colleagues in Calling on Senate Republicans to Hold the Line Against DOD''s Abortion Policies
April 25, 2023
| Posted in Press Releases
Rep. Clyde, Sen. Rubio Seek Answers on Pharmacy Distribution of Abortion Drug
January 31, 2023
| Posted in Press Releases
Rep. Clyde, Sen. Braun Memorialize Lives Lost to Abortion with Day of Tears Resolution
January 24, 2023
| Posted in Press Releases
Rep. Clyde Reintroduces Legislation to Block Biden''s Pro-Abortion Executive Orders
January 20, 2023
| Posted in Press Releases
Rep. Clyde Demands Biden Rescind Undemocratic and Unconstitutional Abortion Executive Order
July 13, 2022
| Posted in Press Releases
All Related News »
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '6e6e789f097b902e37faebd40f9bf63638510bd11e7a0f5debbde26fb40a06f4')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues/issue/?IssueID=14894', 'Second Amendment', 'issues
Second Amendment
Share on Facebook
Share on Twitter
Print this Page
Share by Email
The Founding Fathers enshrined the right to keep and bear arms in the Constitution because they understood the first step toward tyranny is disarming the citizenry. A brief glance through history will show that nearly every totalitarian and dictator rescinded their citizens’ ability to defend themselves before ultimately stripping them of their freedoms.
America is unique in that the Constitution empowers our citizens to defend themselves. Sadly, our Second Amendment rights have been slowly chipped away over the years through unconstitutional laws and undemocratic regulations.
I will always be a stalwart defender of the Second Amendment while serving in Congress. Accordingly, I will oppose all bills and efforts that seek to limit or restrict this right in any way, no matter the circumstances. Instead, I will work tirelessly to restore our Second Amendment rights, which includes eliminating excise taxes on firearms and ammunition, prohibiting “Sporting Use” tests to determine legality of a firearm, and ensuring no federal funds are used to establish a national firearm database, just to name a few efforts, all so that Americans can enjoy the right to bear arms now and in the future.
Related News
Rep. Clyde Leads Call for Strong Pro-2A Attorney General
April 21, 2026
| Posted in Press Releases
Rep. Clyde Introduces Constitutional Hearing Protection Act
May 7, 2025
| Posted in Press Releases
Rep. Clyde, Sen. Marshall Reintroduce Legislation to Combat Biden-Era Anti-Gun Rule
March 27, 2025
| Posted in Press Releases
Rep. Clyde Leads Bill to Prohibit Medicaid-Funded Anti-Gun Programs
December 5, 2024
| Posted in Press Releases
Rep. Clyde Introduces Legislation to Prevent Illegal Aliens from Purchasing Firearms
October 8, 2024
| Posted in Press Releases
All Related News »
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '9b37669dbaec1d4f22244db72ed61311d220e1a89a036d8a9ce35383010c473d')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues/issue/?IssueID=14895', 'Taxation & IRS', 'issues
Taxation & IRS
Share on Facebook
Share on Twitter
Print this Page
Share by Email
Article I, Section 8, Clause 1 of the U.S. Constitution gives Congress the power to lay and collect taxes. Nowhere though does the Constitution say that the federal government can nickel and dime you, in fact, it states that " all Duties, Imposts and Excises shall be uniform throughout the United States." But unfortunately, the tax code as we know it today is far from being "uniform," as it is riddled with loopholes, carve outs, and credits that cater to wealthy special interest groups at the expense of all taxpayers. The American people deserve an equitable system of taxation that provides the means to "pay the Debts and provide for the common Defence and general Welfare of the United States," and no more. To achieve that, we must overhaul the current tax code and abolish the Internal Revenue Service (IRS) altogether.
That’s why I support the FairTax, a system of taxation that abolishes the IRS and replaces it with a one-time, inclusive, federal sales tax on new goods and services. The FairTax creates a level playing field by taxing Americans at the cash register the same and it ensures fairness through the prebate. The prebate essentially untaxes each household monthly, up to the poverty level, to ensure households can purchase necessities. In turn, the prebate ensures that those closest to the poverty level pay a lower overall rate while those earning more pay a higher rate. Bottom line, the FairTax is a bold solution and would make Tax Day each year another Spring day. Most importantly, the FairTax would allow American workers to keep more of their hard-earned paychecks and only pay taxes on what they spend.
Related News
Rep. Clyde Votes Against Swamp''s Tax Bill
January 31, 2024
| Posted in Press Releases
All Related News »
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '6b61d0887090d4d39148e7426c058dde5c3c8a73ca1cccc9151a722eb1db11cb')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'official_page', 'https://clyde.house.gov/issues/issue/?IssueID=14891', 'Veterans', 'issues
Veteran Issues
Share on Facebook
Share on Twitter
Print this Page
Share by Email
As a combat veteran myself, I understand the sacrifices our nation’s warfighters have made in defense of our nation. We owe it to these brave men and women and their families to uphold the promises our country has made to them when they took their oath to serve. We must ensure that our veterans receive the quality care that they earned and deserve. In addition, we must work to eliminate barriers that impede veterans from accessing their education and employment benefits and promote opportunities for success outside of the military. I am committed to being a fierce advocate for those who have served our country in uniform.
More coming soon.
Related News
Rep. Clyde Leads Fellow GOP Navy Veterans in Slamming Active-Duty Drag Queen “Digital Ambassador” to Boost Navy Recruitment
May 16, 2023
| Posted in Press Releases
Rep. Clyde Demands Apology from VA for Politically Motivated Lie
May 11, 2023
| Posted in Press Releases
FOX NEWS: GOP demands apology from Biden’s VA for ‘baseless lie’ about cuts to veterans’ programs
May 11, 2023
| Posted in In the News
Clyde and Cloud Demand VA Rescind Illegal Abortion Rule
September 9, 2022
| Posted in Press Releases
Rep. Clyde signs letter demanding Biden Administration eliminates records backlog for Veterans
April 7, 2021
| Posted in In the News
All Related News »
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', 'ab7bf75ada036c01c7517e437ffb67758298ec998b30fb6ff6a6b3d0edab3378')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'press_release', 'https://clyde.house.gov/news/documentsingle.aspx?DocumentID=3611', 'Rep. Clyde Files Articles of Impeachment Against Obama-Appointed Georgia Judge', 'news
Press Releases
Rep. Clyde Files Articles of Impeachment Against Obama-Appointed Georgia Judge
Share on Facebook
Share on X
Print this Page
Share by Email
Washington,
      June 9, 2026
WASHINGTON, D.C.
— Today, Congressman Andrew Clyde (GA-09) filed three articles of impeachment against Eleanor Ross, a U.S. District Court Judge for the Northern District of Georgia, for high crimes and misdemeanors.
“When judges become political activists or engage in judicial misconduct, Congress bears both the responsibility and the constitutional authority to hold them accountable,”
said Clyde
. “Judge Ross’ deeply disturbing actions prove she is incapable of displaying integrity or showing impartiality. She’s simply unfit to remain a U.S. District Court Judge for the Northern District of Georgia, which is why I’m leading the charge to impeach Judge Ross and ultimately remove her from the bench.”
The three articles of impeachment are summarized below and available
HERE
.
Article I:
Incident to her position as a United States District Court Judge, Eleanor Louise Ross has engaged in conduct with respect to
improper sexual activity in chambers with a law enforcement officer
that is incompatible with the trust and confidence placed in her as a judge.
Article II:
Eleanor Louise Ross engaged in
judicial misconduct by attending a partisan political event
.
Article III:
Eleanor Louise Ross
corruptly obstructed, influenced, or impeded an official proceeding
.
Read the Daily Caller’s exclusive on Rep. Clyde’s articles of impeachment against Judge Ross
HERE
.
Original cosponsors include (7): Representatives Lauren Boebert (CO-04), Sheri Biggs (SC-03), Buddy Carter (GA-01), John Carter (TX-31), Paul Gosar (AZ-09), Andy Harris (MD-01), and Andy Ogles (TN-05).
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '7598300d121512dc6b387643b85fbb3d7addeaae89e94a69403efff3ea4ba87a')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'press_release', 'https://clyde.house.gov/news/documentsingle.aspx?DocumentID=3593', 'Rep. Clyde Applauds Lanier Parks Local Access Act in Action', 'news
Press Releases
Rep. Clyde Applauds Lanier Parks Local Access Act in Action
Share on Facebook
Share on X
Print this Page
Share by Email
Washington,
      May 13, 2026
WASHINGTON, D.C.
—
Today, Congressman Andrew Clyde (GA-09) released the following statement in response to a recent
announcement
that Hall County Parks & Leisure will assume the management of 11 additional recreation sites along Lake Lanier through a new partnership with the U.S. Army Corps of Engineers (USACE):
“I’m thrilled to see my successful legislative effort in action for the Ninth District,”
said Clyde
. “Last year, I offered a simple yet effective solution to help keep Lake Lanier parks open for residents and visitors alike. Due to my hard-fought efforts, this measure was signed into law by President Trump through the appropriations process — delivering a critical win for our beloved Lake Lanier and surrounding communities. I applaud Hall County and the U.S. Army Corps of Engineers’ partnership, and I look forward to these additional recreation sites remaining open, safe, and well-maintained for years to come.”
On January 23rd, President Donald J. Trump signed H.R. 6938, the Fiscal Year 2026 (FY26) Commerce, Justice, Science; Energy and Water Development; and Interior and Environment Appropriations Act, into law. The spending package included Congressman Clyde’s
legislation
to protect and improve Lake Lanier’s recreation sites.
Due to Rep. Clyde’s hard-fought efforts, the FY26 Energy and Water Development appropriations bill included a
provision
(Sec. 109) that allows local partners that manage multiple recreation sites at a U.S. Army Corps of Engineers civil works project to spend collected user fees across all sites they oversee at that project, rather than being limited to using the fees only at the specific site where the funds were collected.
The measure mirrors Rep. Clyde’s
Lanier Parks Local Access Act
, which aims to incentivize local governments to manage recreation sites on civil works projects like Lake Lanier.
Background
Last year — just days ahead of Memorial Day Weekend, the USACE Mobile District, which oversees Lake Lanier,
announced
the temporary closure of 11 Corps managed recreation sites due to staffing shortages.
Weeks later, Rep. Clyde introduced the
Lanier Parks Local Access Act
to help keep Lake Lanier’s parks and boat ramps open by incentivizing local governments to manage more sites.
Less than one year later, Rep. Clyde’s measure was signed into law by President Trump through the FY26 appropriations process and utilized by Hall County to manage 11 additional sites on Lake Lanier, including seven that were temporarily closed ahead of Memorial Day last year.
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', 'c39a8d62d5cae1a544375670893658e93ace95d98da9406baf814be1f0db8038')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

INSERT INTO public.rep_sources (rep_id, source_type, url, title, content, content_hash) VALUES
  (20, 'press_release', 'https://clyde.house.gov/news/documentsingle.aspx?DocumentID=3568', 'Rep. Clyde Congratulates North Gwinnett Seniors on U.S. Service Academy Appointments', 'news
Press Releases
Rep. Clyde Congratulates North Gwinnett Seniors on U.S. Service Academy Appointments
Share on Facebook
Share on X
Print this Page
Share by Email
Gainesville,
      May 8, 2026
GAINESVILLE, GA
— This week, Congressman Andrew Clyde (GA-09) honored North Gwinnett High School seniors Jenny Lee and Kalil Mazone during a signing ceremony celebrating their U.S. Service Academy appointments. Rep. Clyde proudly
nominated
the students for the prestigious appointments.
On Tuesday, North Gwinnett High School hosted family and faculty to recognize Jenny and Kalil’s achievements and dedication to military service. Jenny received an appointment to the U.S. Naval Academy, and Kalil received an appointment to and committed to play football at the U.S. Air Force Academy. After delivering remarks highlighting their accomplishments, Congressman Clyde presented both students with Congressional Certificates of Congratulations and Pledges of Commitment for signature.
“Jenny and Kalil are two exceptional young Georgians with bright futures,”
said Clyde
. “As a Navy combat veteran, I have no doubt that Jenny’s academic excellence, servant’s heart, and self-discipline have equipped her for success at the Naval Academy. Both on and off the field, Kalil is a tenacious, talented leader with a selfless strength for others, which will serve his fellow cadets well at the Air Force Academy. I’m confident these two will continue making the Ninth District proud in their future endeavors and military service.”
Background
Each year, Congressman Clyde nominates eligible candidates for appointment to four of the five U.S. Service Academies: U.S. Military Academy (USMA), West Point, NY; the U.S. Naval Academy (USNA), Annapolis, MD; the U.S. Air Force Academy (USAFA), Colorado Springs, CO; and the U.S. Merchant Marine Academy (USMMA), Kings Point, NY. The fifth academy, the U.S. Coast Guard Academy (USCGA), New London, CT, does not require a congressional nomination for appointment.
Office Locations
Office Locations
Washington, DC Office
445 Cannon HOB
Washington, DC 20515
Phone:
(202) 225-9893
Fax:
(202) 226-1224
Gainesville District Office
210 Washington St NW, Suite 202
Gainesville, GA 30501
Phone:
(470) 768-6520', '5080ecd5ae76eba2702c1fc88c16c2b991f190a4df74df5014a661f2f03c8d6f')
ON CONFLICT (rep_id, content_hash) DO NOTHING;

