-- migrations/0001_ballot_lifecycle.sql
-- Phase 3.5: ballot lifecycle (elections -> contests -> candidacies).
-- Applied to the remote project via Supabase MCP 2026-06-11. Captured here so
-- schema isn't MCP-only (the rep_positions/rep_sources schema from phase 3.1 was
-- never captured; this folder starts fixing that).
--
-- Goal: "pull what Vote411 pulls" -- the full prospective ballot for an address
-- with ALL candidates per race, not just incumbents. A candidate is a person-row
-- in public.representatives, so the inference (rep_sources/rep_positions) and
-- district-matching stacks apply to challengers for free.

-- A dated ballot event in a state.
create table public.elections (
  id            bigint generated by default as identity primary key,
  state         text not null default 'GA',
  name          text not null,
  election_date date not null,
  type          text not null check (type in ('primary','primary_runoff','general','general_runoff','special')),
  is_partisan   boolean not null default false,
  created_at    timestamptz not null default now(),
  unique (state, election_date, type)
);

-- One office decided in one election, scoped to a district (or statewide).
-- District columns mirror public.users.* so a contest matches a voter exactly
-- the way representatives do. For a partisan primary, each party's ballot is its
-- own contest row (party set); for a general/nonpartisan race, party is null.
create table public.contests (
  id                          bigint generated by default as identity primary key,
  election_id                 bigint not null references public.elections(id) on delete cascade,
  office_name                 text not null,
  level                       text not null check (level in ('federal','state','county','city','school')),
  is_statewide                boolean not null default false,
  party                       text,
  seats                       integer not null default 1,
  cong_district               text,
  state_senate_district       text,
  state_house_district        text,
  county_commission_district  text,
  city_council_district       text,
  school_board_district       text,
  county                      text,
  city                        text,
  -- links general<-primary and runoff<-source across the lifecycle
  parent_contest_id           bigint references public.contests(id) on delete set null,
  created_at                  timestamptz not null default now()
);

-- A person (representatives row) running in a contest.
create table public.candidacies (
  id            bigint generated by default as identity primary key,
  contest_id    bigint not null references public.contests(id) on delete cascade,
  rep_id        bigint not null references public.representatives(id) on delete cascade,
  party         text,
  is_incumbent  boolean not null default false,
  ballot_order  integer,
  status        text not null default 'qualified'
                  check (status in ('qualified','withdrawn','disqualified','advanced','won','lost')),
  source_url    text,
  created_at    timestamptz not null default now(),
  unique (contest_id, rep_id)
);

create index contests_election_idx   on public.contests (election_id);
create index contests_cong_idx       on public.contests (cong_district);
create index contests_ssen_idx       on public.contests (state_senate_district);
create index contests_shouse_idx     on public.contests (state_house_district);
create index contests_ccomm_idx      on public.contests (county_commission_district);
create index contests_sboard_idx     on public.contests (school_board_district);
create index contests_county_idx     on public.contests (county);
create index candidacies_contest_idx on public.candidacies (contest_id);
create index candidacies_rep_idx     on public.candidacies (rep_id);

-- RLS: public read, no client writes (service role bypasses for seeding).
alter table public.elections   enable row level security;
alter table public.contests    enable row level security;
alter table public.candidacies enable row level security;

create policy "elections public read"   on public.elections   for select using (true);
create policy "contests public read"     on public.contests    for select using (true);
create policy "candidacies public read"  on public.candidacies for select using (true);
