-- seeds/00_issues.sql
-- Canonical issue list. Source of truth: shared/issues.json (phase 3.4 rewrite).
-- Idempotent: ON CONFLICT (id) upserts text/scope/flags. Safe to re-run.

insert into public.issues (id, text, scope, onboarding, needs_review) values
  (101, 'Should there be strict limits on money in politics, even if that restricts how much individuals and groups can spend to support causes they believe in?', 'national', false, false),
  (102, 'When making gun policy, should reducing gun violence generally take priority over protecting gun owners'' rights?', 'national', true, false),
  (103, 'Should abortion be legal in most circumstances?', 'national', true, false),
  (104, 'Should the government do more to solve problems and help people, even if that means higher taxes?', 'national', true, false),
  (105, 'Should the wealthiest Americans pay significantly higher taxes to reduce economic inequality?', 'national', true, false),
  (106, 'Should the government guarantee health coverage for everyone, even if it means higher taxes and a larger government role in healthcare?', 'national', true, false),
  (107, 'When environmental protection and economic growth conflict, should protecting the environment generally come first?', 'national', true, false),
  (108, 'Should most undocumented immigrants already living in the U.S. have a path to legal status and eventual citizenship?', 'national', true, false),
  (109, 'Should the criminal justice system focus more on rehabilitation than on tougher sentencing and policing?', 'national', true, false),
  (110, 'Should the U.S. reduce its military involvement around the world and focus more on problems at home?', 'national', true, false),
  (111, 'Should transgender women and girls be allowed to compete on female sports teams?', 'national', true, false),
  (112, 'Should same-sex marriage be protected by federal law?', 'national', false, false),
  (113, 'Should minors be able to receive gender-affirming medical care when their parents consent?', 'national', false, false),
  (114, 'Should public schools be allowed to teach students about gender identity and sexual orientation?', 'national', false, false),
  (115, 'Should local school boards be able to remove books from school libraries because of their content?', 'national', false, false),
  (116, 'Should business owners be allowed to refuse services for a same-sex wedding based on their religious beliefs?', 'national', false, false),
  (117, 'Should the death penalty be abolished?', 'national', false, false),
  (118, 'Should terminally ill adults be allowed to end their lives with a doctor''s help?', 'national', false, false),
  (119, 'Should marijuana be legal for recreational use nationwide?', 'national', false, false),
  (120, 'Should certain psychedelics be allowed for mental-health treatment under medical supervision?', 'national', false, false),
  (121, 'Should children be required to be vaccinated to attend public schools?', 'national', false, false),
  (122, 'Should public college be tuition-free for in-state students?', 'national', false, false),
  (123, 'Should employers be required to provide paid family and medical leave?', 'national', false, false),
  (124, 'Should the government provide universal, affordable childcare?', 'national', false, false),
  (125, 'Should the government provide every adult a guaranteed basic income?', 'national', false, false),
  (126, 'Should the federal minimum wage be raised substantially above $7.25 an hour?', 'national', false, false),
  (127, 'Should the government cap how much landlords can raise rent?', 'national', false, false),
  (128, 'Should parents be able to use public funds to send their children to private schools?', 'national', false, false),
  (129, 'Should the U.S. expand nuclear power to help meet energy needs and reduce emissions?', 'national', false, false),
  (130, 'Should the U.S. tighten border security and reduce overall immigration levels?', 'national', false, false),
  (131, 'Should police be restricted from using facial-recognition technology to identify people?', 'national', false, false),
  (132, 'Should speech that many people consider hateful still be protected as free speech?', 'national', false, false),
  (133, 'Should the government more tightly regulate what content social media companies are allowed to host or remove?', 'national', false, false),
  (134, 'Should the government break up large corporations that have grown too powerful?', 'national', false, false),
  (135, 'Should the U.S. limit free trade to protect American jobs and industries, even if it raises prices for consumers?', 'national', false, false),
  (136, 'Should members of Congress face term limits?', 'national', false, false),
  (137, 'Should voting district lines be drawn by an independent body rather than by politicians?', 'national', false, false),
  (138, 'Should the President be elected by national popular vote instead of the Electoral College?', 'national', false, false),
  (201, 'Should Georgia expand Medicaid to cover more low-income adults?', 'state', false, false),
  (202, 'Should Georgia eliminate its state income tax, even if that means raising sales taxes?', 'state', false, false),
  (203, 'Should Georgia make registering and voting easier, even if that means looser verification requirements?', 'state', false, false),
  (204, 'Should Georgia legalize recreational marijuana for adults?', 'state', false, false),
  (205, 'Should Georgia keep the limits on citizen''s arrests it passed after the Ahmaud Arbery case?', 'state', false, false),
  (206, 'Should Georgia require a permit and background check to carry a concealed handgun in public?', 'state', false, false),
  (207, 'Should Georgia set a state minimum wage higher than the federal $7.25 an hour?', 'state', false, false),
  (208, 'Should Georgia legalize casinos and sports betting?', 'state', false, false),
  (209, 'Should Georgia pass a statewide law banning discrimination based on sexual orientation and gender identity?', 'state', false, false),
  (210, 'Should Georgia keep its current law banning most abortions after about six weeks?', 'state', false, false),
  (301, 'Should Hall County raise property taxes if that is what it takes to better fund local public schools?', 'county', false, false),
  (302, 'Should the Hall County Sheriff''s office continue partnering with federal agents to identify and detain undocumented immigrants?', 'county', false, false),
  (303, 'Should Hall County spend more to protect Lake Lanier''s water quality, even if it limits nearby development?', 'county', false, false),
  (304, 'Should Hall County require new housing developments to set aside land for parks and greenspace?', 'county', false, false),
  (305, 'Should Hall County expand public transportation beyond today''s limited on-demand service?', 'county', false, false),
  (401, 'Should Gainesville require new housing developments to include affordable units?', 'city', false, true),
  (402, 'Should Gainesville concentrate growth in its existing downtown and core rather than expanding outward?', 'city', false, false),
  (403, 'Should Gainesville increase funding for its police department?', 'city', false, false),
  (404, 'Should Gainesville require new buildings near the downtown square to follow historic design rules, even if it costs builders more?', 'city', false, false),
  (405, 'Should Gainesville keep hiring private companies for city services like trash collection rather than providing them itself?', 'city', false, true)
on conflict (id) do update set
  text         = excluded.text,
  scope        = excluded.scope,
  onboarding   = excluded.onboarding,
  needs_review = excluded.needs_review;
