-- GA state legislature seed, scraped from Wikipedia 2026-06-10.
-- 55 senators + 179 house members (Wikipedia listed 1 vacancy in each).
-- Districts encoded to match the TIGER shapefile format:
--   state_senate_district: lstrip-of-zeros string ("49")
--   state_assembly_district: 3-char zero-padded string ("029")

INSERT INTO public.representatives (name, position, state, party, state_senate_district, state_assembly_district) VALUES
  ('Ben Watson', 'State Senator', 'GA', 'R', '1', NULL),
  ('Derek Mallow', 'State Senator', 'GA', 'D', '2', NULL),
  ('Mike Hodges', 'State Senator', 'GA', 'R', '3', NULL),
  ('Billy Hickman', 'State Senator', 'GA', 'R', '4', NULL),
  ('Sheikh Rahman', 'State Senator', 'GA', 'D', '5', NULL),
  ('Matt Brass', 'State Senator', 'GA', 'R', '6', NULL),
  ('Russ Goodman', 'State Senator', 'GA', 'R', '8', NULL),
  ('Nikki Merritt', 'State Senator', 'GA', 'D', '9', NULL),
  ('Emanuel Jones', 'State Senator', 'GA', 'D', '10', NULL),
  ('Sam Watson', 'State Senator', 'GA', 'R', '11', NULL),
  ('Freddie Sims', 'State Senator', 'GA', 'D', '12', NULL),
  ('Carden Summers', 'State Senator', 'GA', 'R', '13', NULL),
  ('Josh McLaurin', 'State Senator', 'GA', 'D', '14', NULL),
  ('Ed Harbison', 'State Senator', 'GA', 'D', '15', NULL),
  ('Marty Harbin', 'State Senator', 'GA', 'R', '16', NULL),
  ('Gail Davenport', 'State Senator', 'GA', 'D', '17', NULL),
  ('Steven McNeel', 'State Senator', 'GA', 'R', '18', NULL),
  ('Blake Tillery', 'State Senator', 'GA', 'R', '19', NULL),
  ('Larry Walker III', 'State Senator', 'GA', 'R', '20', NULL),
  ('Jason Dickerson', 'State Senator', 'GA', 'R', '21', NULL),
  ('Harold V. Jones II', 'State Senator', 'GA', 'D', '22', NULL),
  ('Max Burns', 'State Senator', 'GA', 'R', '23', NULL),
  ('Lee Anderson', 'State Senator', 'GA', 'R', '24', NULL),
  ('Rick Williams', 'State Senator', 'GA', 'R', '25', NULL),
  ('David Lucas', 'State Senator', 'GA', 'D', '26', NULL),
  ('Greg Dolezal', 'State Senator', 'GA', 'R', '27', NULL),
  ('Donzella James', 'State Senator', 'GA', 'D', '28', NULL),
  ('Randy Robertson', 'State Senator', 'GA', 'R', '29', NULL),
  ('Tim Bearden', 'State Senator', 'GA', 'R', '30', NULL),
  ('Jason Anavitarte', 'State Senator', 'GA', 'R', '31', NULL),
  ('Kay Kirkpatrick', 'State Senator', 'GA', 'R', '32', NULL),
  ('Michael Rhett', 'State Senator', 'GA', 'D', '33', NULL),
  ('Kenya Wicks', 'State Senator', 'GA', 'D', '34', NULL),
  ('Jaha Howard', 'State Senator', 'GA', 'D', '35', NULL),
  ('Nan Orrock', 'State Senator', 'GA', 'D', '36', NULL),
  ('Ed Setzler', 'State Senator', 'GA', 'R', '37', NULL),
  ('RaShaun Kemp', 'State Senator', 'GA', 'D', '38', NULL),
  ('Sonya Halpern', 'State Senator', 'GA', 'D', '39', NULL),
  ('Sally Harrell', 'State Senator', 'GA', 'D', '40', NULL),
  ('Kim Jackson', 'State Senator', 'GA', 'D', '41', NULL),
  ('Brian Strickland', 'State Senator', 'GA', 'R', '42', NULL),
  ('Tonya Anderson', 'State Senator', 'GA', 'D', '43', NULL),
  ('Elena Parent', 'State Senator', 'GA', 'D', '44', NULL),
  ('Clint Dixon', 'State Senator', 'GA', 'R', '45', NULL),
  ('Bill Cowsert', 'State Senator', 'GA', 'R', '46', NULL),
  ('Frank Ginn', 'State Senator', 'GA', 'R', '47', NULL),
  ('Shawn Still', 'State Senator', 'GA', 'R', '48', NULL),
  ('Drew Echols', 'State Senator', 'GA', 'R', '49', NULL),
  ('Bo Hatchett', 'State Senator', 'GA', 'R', '50', NULL),
  ('Steve Gooch', 'State Senator', 'GA', 'R', '51', NULL),
  ('Chuck Hufstetler', 'State Senator', 'GA', 'R', '52', NULL),
  ('Lanny Thomas', 'State Senator', 'GA', 'R', '53', NULL),
  ('Chuck Payne', 'State Senator', 'GA', 'R', '54', NULL),
  ('Randal Mangham', 'State Senator', 'GA', 'D', '55', NULL),
  ('John Albers', 'State Senator', 'GA', 'R', '56', NULL),
  ('Mike Cameron', 'State Representative', 'GA', 'R', NULL, '001'),
  ('Steve Tarvin', 'State Representative', 'GA', 'R', NULL, '002'),
  ('Mitchell Horner', 'State Representative', 'GA', 'R', NULL, '003'),
  ('Kasey Carpenter', 'State Representative', 'GA', 'R', NULL, '004'),
  ('Matt Barton', 'State Representative', 'GA', 'R', NULL, '005'),
  ('Jason Ridley', 'State Representative', 'GA', 'R', NULL, '006'),
  ('Johnny Chastain', 'State Representative', 'GA', 'R', NULL, '007'),
  ('Stan Gunter', 'State Representative', 'GA', 'R', NULL, '008'),
  ('Will Wade', 'State Representative', 'GA', 'R', NULL, '009'),
  ('Victor Anderson', 'State Representative', 'GA', 'R', NULL, '010'),
  ('Rick Jasperse', 'State Representative', 'GA', 'R', NULL, '011'),
  ('Eddie Lumsden', 'State Representative', 'GA', 'R', NULL, '012'),
  ('Katie Dempsey', 'State Representative', 'GA', 'R', NULL, '013'),
  ('Mitchell Scoggins', 'State Representative', 'GA', 'R', NULL, '014'),
  ('Matthew Gambill', 'State Representative', 'GA', 'R', NULL, '015'),
  ('Trey Kelley', 'State Representative', 'GA', 'R', NULL, '016'),
  ('Martin Momtahan', 'State Representative', 'GA', 'R', NULL, '017'),
  ('Tyler Smith', 'State Representative', 'GA', 'R', NULL, '018'),
  ('Joseph Gullett', 'State Representative', 'GA', 'R', NULL, '019'),
  ('Charlice Byrd', 'State Representative', 'GA', 'R', NULL, '020'),
  ('Brad Thomas', 'State Representative', 'GA', 'R', NULL, '021'),
  ('Jordan Ridley', 'State Representative', 'GA', 'R', NULL, '022'),
  ('Bill Fincher', 'State Representative', 'GA', 'R', NULL, '023'),
  ('Carter Barrett', 'State Representative', 'GA', 'R', NULL, '024'),
  ('Todd Jones', 'State Representative', 'GA', 'R', NULL, '025'),
  ('Lauren McDonald', 'State Representative', 'GA', 'R', NULL, '026'),
  ('Lee Hawkins', 'State Representative', 'GA', 'R', NULL, '027'),
  ('Brent Cox', 'State Representative', 'GA', 'R', NULL, '028'),
  ('Matt Dubnik', 'State Representative', 'GA', 'R', NULL, '029'),
  ('Derrick McCollum', 'State Representative', 'GA', 'R', NULL, '030'),
  ('Emory Dunahoo', 'State Representative', 'GA', 'R', NULL, '031'),
  ('Chris Erwin', 'State Representative', 'GA', 'R', NULL, '032'),
  ('Alan Powell', 'State Representative', 'GA', 'R', NULL, '033'),
  ('Devan Seabaugh', 'State Representative', 'GA', 'R', NULL, '034'),
  ('Lisa Campbell', 'State Representative', 'GA', 'D', NULL, '035'),
  ('Ginny Ehrhart', 'State Representative', 'GA', 'R', NULL, '036'),
  ('Mary Frances Williams', 'State Representative', 'GA', 'D', NULL, '037'),
  ('David Wilkerson', 'State Representative', 'GA', 'D', NULL, '038'),
  ('Terry Cummings', 'State Representative', 'GA', 'D', NULL, '039'),
  ('Kimberly New', 'State Representative', 'GA', 'R', NULL, '040'),
  ('Michael Smith', 'State Representative', 'GA', 'D', NULL, '041'),
  ('Gabriel Sanchez', 'State Representative', 'GA', 'D', NULL, '042'),
  ('Solomon Adesanya', 'State Representative', 'GA', 'D', NULL, '043'),
  ('Don Parsons', 'State Representative', 'GA', 'R', NULL, '044'),
  ('Sharon Cooper', 'State Representative', 'GA', 'R', NULL, '045'),
  ('John Carson', 'State Representative', 'GA', 'R', NULL, '046'),
  ('Jan Jones', 'State Representative', 'GA', 'R', NULL, '047'),
  ('Scott Hilton', 'State Representative', 'GA', 'R', NULL, '048'),
  ('Chuck Martin', 'State Representative', 'GA', 'R', NULL, '049'),
  ('Michelle Au', 'State Representative', 'GA', 'D', NULL, '050'),
  ('Esther Panitch', 'State Representative', 'GA', 'D', NULL, '051'),
  ('Shea Roberts', 'State Representative', 'GA', 'D', NULL, '052'),
  ('Deborah Silcox', 'State Representative', 'GA', 'R', NULL, '053'),
  ('Betsy Holland', 'State Representative', 'GA', 'D', NULL, '054'),
  ('Inga Willis', 'State Representative', 'GA', 'D', NULL, '055'),
  ('Bryce Berry', 'State Representative', 'GA', 'D', NULL, '056'),
  ('Stacey Evans', 'State Representative', 'GA', 'D', NULL, '057'),
  ('Park Cannon', 'State Representative', 'GA', 'D', NULL, '058'),
  ('Phil Olaleye', 'State Representative', 'GA', 'D', NULL, '059'),
  ('Sheila Jones', 'State Representative', 'GA', 'D', NULL, '060'),
  ('Mekyah McQueen', 'State Representative', 'GA', 'D', NULL, '061'),
  ('Tanya F. Miller', 'State Representative', 'GA', 'D', NULL, '062'),
  ('Kim Schofield', 'State Representative', 'GA', 'D', NULL, '063'),
  ('Sylvia Wayfer Baker', 'State Representative', 'GA', 'D', NULL, '064'),
  ('Robert Dawson', 'State Representative', 'GA', 'D', NULL, '065'),
  ('Kimberly Alexander', 'State Representative', 'GA', 'D', NULL, '066'),
  ('Lydia Glaize', 'State Representative', 'GA', 'D', NULL, '067'),
  ('Derrick Jackson', 'State Representative', 'GA', 'D', NULL, '068'),
  ('Debra Bazemore', 'State Representative', 'GA', 'D', NULL, '069'),
  ('Lynn Smith', 'State Representative', 'GA', 'R', NULL, '070'),
  ('Justin Howard', 'State Representative', 'GA', 'R', NULL, '071'),
  ('David Huddleston', 'State Representative', 'GA', 'R', NULL, '072'),
  ('Josh Bonner', 'State Representative', 'GA', 'R', NULL, '073'),
  ('Robert Flournoy', 'State Representative', 'GA', 'D', NULL, '074'),
  ('Eric Bell II', 'State Representative', 'GA', 'D', NULL, '075'),
  ('Sandra Scott', 'State Representative', 'GA', 'D', NULL, '076'),
  ('Rhonda Burnough', 'State Representative', 'GA', 'D', NULL, '077'),
  ('Demetrius Douglas', 'State Representative', 'GA', 'D', NULL, '078'),
  ('Yasmin Neal', 'State Representative', 'GA', 'D', NULL, '079'),
  ('Long Tran', 'State Representative', 'GA', 'D', NULL, '080'),
  ('Noelle Kahaian', 'State Representative', 'GA', 'R', NULL, '081'),
  ('Karen Mathiak', 'State Representative', 'GA', 'R', NULL, '082'),
  ('Karen Lupton', 'State Representative', 'GA', 'D', NULL, '083'),
  ('Mary Margaret Oliver', 'State Representative', 'GA', 'D', NULL, '084'),
  ('Karla Drenner', 'State Representative', 'GA', 'D', NULL, '085'),
  ('Imani Barnes', 'State Representative', 'GA', 'D', NULL, '086'),
  ('Viola Davis', 'State Representative', 'GA', 'D', NULL, '087'),
  ('Billy Mitchell', 'State Representative', 'GA', 'D', NULL, '088'),
  ('Omari Crawford', 'State Representative', 'GA', 'D', NULL, '089'),
  ('Saira Draper', 'State Representative', 'GA', 'D', NULL, '090'),
  ('Angela Moore', 'State Representative', 'GA', 'D', NULL, '091'),
  ('Rhonda Taylor', 'State Representative', 'GA', 'D', NULL, '092'),
  ('Doreen Carter', 'State Representative', 'GA', 'D', NULL, '093'),
  ('Venola Mason', 'State Representative', 'GA', 'D', NULL, '094'),
  ('Dar''shun Kendrick', 'State Representative', 'GA', 'D', NULL, '095'),
  ('Arlene Beckles', 'State Representative', 'GA', 'D', NULL, '096'),
  ('Ruwa Romman', 'State Representative', 'GA', 'D', NULL, '097'),
  ('Marvin Lim', 'State Representative', 'GA', 'D', NULL, '098'),
  ('Matt Reeves', 'State Representative', 'GA', 'R', NULL, '099'),
  ('David Clark', 'State Representative', 'GA', 'R', NULL, '100'),
  ('Scott Holcomb', 'State Representative', 'GA', 'D', NULL, '101'),
  ('Gabe Okoye', 'State Representative', 'GA', 'D', NULL, '102'),
  ('Soo Hong', 'State Representative', 'GA', 'R', NULL, '103'),
  ('Chuck Efstration', 'State Representative', 'GA', 'R', NULL, '104'),
  ('Sandy Donatucci', 'State Representative', 'GA', 'R', NULL, '105'),
  ('Akbar Ali', 'State Representative', 'GA', 'D', NULL, '106'),
  ('Sam Park', 'State Representative', 'GA', 'D', NULL, '107'),
  ('Jasmine Clark', 'State Representative', 'GA', 'D', NULL, '108'),
  ('Dewey McClain', 'State Representative', 'GA', 'D', NULL, '109'),
  ('Segun Adeyina', 'State Representative', 'GA', 'D', NULL, '110'),
  ('Reynaldo Martinez', 'State Representative', 'GA', 'R', NULL, '111'),
  ('Bruce Williamson', 'State Representative', 'GA', 'R', NULL, '112'),
  ('Sharon Henderson', 'State Representative', 'GA', 'D', NULL, '113'),
  ('Tim Fleming', 'State Representative', 'GA', 'R', NULL, '114'),
  ('Regina Lewis-Ward', 'State Representative', 'GA', 'D', NULL, '115'),
  ('El-Mahdi Holly', 'State Representative', 'GA', 'D', NULL, '116'),
  ('Mary Ann Santos', 'State Representative', 'GA', 'D', NULL, '117'),
  ('Clint Crowe', 'State Representative', 'GA', 'R', NULL, '118'),
  ('Holt Persinger', 'State Representative', 'GA', 'R', NULL, '119'),
  ('Houston Gaines', 'State Representative', 'GA', 'R', NULL, '120'),
  ('Eric Gisler', 'State Representative', 'GA', 'D', NULL, '121'),
  ('Spencer Frye', 'State Representative', 'GA', 'D', NULL, '122'),
  ('Rob Leverett', 'State Representative', 'GA', 'R', NULL, '123'),
  ('Trey Rhodes', 'State Representative', 'GA', 'R', NULL, '124'),
  ('Gary Richardson', 'State Representative', 'GA', 'R', NULL, '125'),
  ('L. C. Myles', 'State Representative', 'GA', 'D', NULL, '126'),
  ('Mark Newton', 'State Representative', 'GA', 'R', NULL, '127'),
  ('Mack Jackson', 'State Representative', 'GA', 'D', NULL, '128'),
  ('Karlton Howard', 'State Representative', 'GA', 'D', NULL, '129'),
  ('Sheila Nelson', 'State Representative', 'GA', 'D', NULL, '130'),
  ('Rob Clifton', 'State Representative', 'GA', 'R', NULL, '131'),
  ('Brian Prince', 'State Representative', 'GA', 'D', NULL, '132'),
  ('Danny Mathis', 'State Representative', 'GA', 'R', NULL, '133'),
  ('Robert Dickey', 'State Representative', 'GA', 'R', NULL, '134'),
  ('Beth Camp', 'State Representative', 'GA', 'R', NULL, '135'),
  ('David Jenkins', 'State Representative', 'GA', 'R', NULL, '136'),
  ('Debbie Buckner', 'State Representative', 'GA', 'D', NULL, '137'),
  ('Vance Smith', 'State Representative', 'GA', 'R', NULL, '138'),
  ('Carmen Rice', 'State Representative', 'GA', 'R', NULL, '139'),
  ('Tremaine Teddy Reese', 'State Representative', 'GA', 'D', NULL, '140'),
  ('Carolyn Hugley', 'State Representative', 'GA', 'D', NULL, '141'),
  ('Miriam Paris', 'State Representative', 'GA', 'D', NULL, '142'),
  ('Anissa Jones', 'State Representative', 'GA', 'D', NULL, '143'),
  ('Dale Washburn', 'State Representative', 'GA', 'R', NULL, '144'),
  ('Tangie Herring', 'State Representative', 'GA', 'D', NULL, '145'),
  ('Shaw Blackmon', 'State Representative', 'GA', 'R', NULL, '146'),
  ('Bethany Ballard', 'State Representative', 'GA', 'R', NULL, '147'),
  ('Noel Williams Jr.', 'State Representative', 'GA', 'R', NULL, '148'),
  ('Floyd Griffin', 'State Representative', 'GA', 'D', NULL, '149'),
  ('Patty Marie Stinson', 'State Representative', 'GA', 'D', NULL, '150'),
  ('Mike Cheokas', 'State Representative', 'GA', 'R', NULL, '151'),
  ('Bill Yearta', 'State Representative', 'GA', 'R', NULL, '152'),
  ('David Sampson', 'State Representative', 'GA', 'D', NULL, '153'),
  ('Gerald Greene', 'State Representative', 'GA', 'R', NULL, '154'),
  ('Matt Hatchett', 'State Representative', 'GA', 'R', NULL, '155'),
  ('Leesa Hagan', 'State Representative', 'GA', 'R', NULL, '156'),
  ('Bill Werkheiser', 'State Representative', 'GA', 'R', NULL, '157'),
  ('Butch Parrish', 'State Representative', 'GA', 'R', NULL, '158'),
  ('Jon G. Burns', 'State Representative', 'GA', 'R', NULL, '159'),
  ('Lehman Franklin', 'State Representative', 'GA', 'R', NULL, '160'),
  ('Bill Hitchens', 'State Representative', 'GA', 'R', NULL, '161'),
  ('Carl Gilliard', 'State Representative', 'GA', 'D', NULL, '162'),
  ('Anne Allen Westbrook', 'State Representative', 'GA', 'D', NULL, '163'),
  ('Ron Stephens', 'State Representative', 'GA', 'R', NULL, '164'),
  ('Edna Jackson', 'State Representative', 'GA', 'D', NULL, '165'),
  ('Jesse Petrea', 'State Representative', 'GA', 'R', NULL, '166'),
  ('Buddy DeLoach', 'State Representative', 'GA', 'R', NULL, '167'),
  ('Al Williams', 'State Representative', 'GA', 'D', NULL, '168'),
  ('Angie O''Steen', 'State Representative', 'GA', 'R', NULL, '169'),
  ('Jaclyn Ford', 'State Representative', 'GA', 'R', NULL, '170'),
  ('Joe Campbell', 'State Representative', 'GA', 'R', NULL, '171'),
  ('Charles Cannon', 'State Representative', 'GA', 'R', NULL, '172'),
  ('Darlene Taylor', 'State Representative', 'GA', 'R', NULL, '173'),
  ('John Corbett', 'State Representative', 'GA', 'R', NULL, '174'),
  ('John LaHood', 'State Representative', 'GA', 'R', NULL, '175'),
  ('James Burchett', 'State Representative', 'GA', 'R', NULL, '176'),
  ('Steven Meeks', 'State Representative', 'GA', 'R', NULL, '178'),
  ('Rick Townsend', 'State Representative', 'GA', 'R', NULL, '179'),
  ('Steven Sainz', 'State Representative', 'GA', 'R', NULL, '180')
ON CONFLICT (name, position) DO UPDATE SET
  state = EXCLUDED.state,
  party = EXCLUDED.party,
  state_senate_district = EXCLUDED.state_senate_district,
  state_assembly_district = EXCLUDED.state_assembly_district;
