-- seeds/22_flagship_bios.sql
-- Light-resume bios for flagship candidates (engagement workstream #3), sourced 2026-06-19 (1 Sonnet
-- agent, all cited; neutral/factual, no criminal history per scope). Rendered in the profile
-- "Background" section. Idempotent (UPDATE by id; Reynolds by name). Source URLs in comments.
-- Dollar-quoted to avoid apostrophe escaping.

update public.representatives set bio = $b$Andrew Clyde has represented Georgia's 9th Congressional District in the U.S. House since January 2021. He served 28 years in naval aviation and the U.S. Navy Seabees, retiring at the rank of Commander in 2013, including three combat deployments to Iraq and Kuwait. He founded Clyde Armory, a firearms retail and gunsmithing business in Athens, Georgia, in 1991. Clyde holds a bachelor's degree in accounting and business management from Bethel University (Indiana) and an MBA from the University of Georgia.$b$ where id = 20;  -- en.wikipedia.org/wiki/Andrew_Clyde

update public.representatives set bio = $b$Mike Collins has represented Georgia's 10th Congressional District in the U.S. House since January 2023, first elected in 2022. He is the owner of Collins Trucking Company, a family business based in Jackson, Georgia. Collins won the 2026 Republican primary runoff for the U.S. Senate seat held by Jon Ossoff and is the 2026 Republican nominee for that seat. He earned a bachelor's degree from Georgia State University in 1990.$b$ where id = 21;  -- ballotpedia.org/Mike_Collins_(Georgia)

update public.representatives set bio = $b$Jon Ossoff has served as a U.S. Senator from Georgia since January 2021, defeating incumbent David Perdue in a January 5, 2021 runoff election. Before entering elected office, he worked as a congressional aide for Rep. Hank Johnson and then as CEO of Insight TWI, a documentary film production company that investigates corruption and organized crime. Ossoff holds a bachelor's degree from Georgetown University's School of Foreign Service and a master's degree from the London School of Economics.$b$ where id = 10;  -- ballotpedia.org/Jon_Ossoff

update public.representatives set bio = $b$Rick Jackson is a Georgia businessman and the 2026 Republican nominee for Governor of Georgia, having defeated Lieutenant Governor Burt Jones in the June 16, 2026 Republican primary runoff. He founded Jackson Healthcare, a healthcare staffing and services company headquartered in Alpharetta, Georgia, starting his first medical recruitment business in 1978. Jackson attended Lipscomb University in Nashville to study business before leaving due to financial constraints, and is a graduate of Greater Atlanta Christian School.$b$ where id = 281;  -- ballotpedia.org/Rick_Jackson_(Georgia)

update public.representatives set bio = $b$Keisha Lance Bottoms served as the 60th Mayor of Atlanta from January 2018 to January 2022, and previously represented Atlanta City Council District 11 from 2010 to 2018. After leaving the mayoralty, she served in the Biden White House as Senior Advisor to the President and Director of the Office of Public Engagement from July 2022 to April 2023. She is the 2026 Democratic nominee for Governor of Georgia. Bottoms holds a bachelor's degree in communications from Florida A&M University and a J.D. from Georgia State University College of Law.$b$ where id = 282;  -- ballotpedia.org/Keisha_Lance_Bottoms

update public.representatives set bio = $b$Drew Echols has represented Georgia State Senate District 49, covering most of Hall County, since January 2025, succeeding his wife Shelly Echols in the seat. He has spent over two decades working in his family's operation, Jaemor Farms, a multi-generational fruit and vegetable farm in Hall County, and served as president of the Georgia Fruit and Vegetable Growers Association from 2021 to 2022. He is a graduate of East Hall High School and completed the Leadership Georgia program in 2015.$b$ where id = 73;  -- ballotpedia.org/Drew_Echols

update public.representatives set bio = $b$Matt Dubnik has represented Georgia House of Representatives District 29, which covers part of Gainesville and Hall County, since January 2017. He works as a small business owner and marketing consultant and was born and raised in Gainesville, Georgia. Dubnik holds a bachelor's degree from the Georgia Institute of Technology.$b$ where id = 109;  -- ballotpedia.org/Matt_Dubnik

update public.representatives set bio = $b$Greg Dolezal has represented Georgia State Senate District 27 (Forsyth County) since January 2019 and is the 2026 Republican nominee for Lieutenant Governor of Georgia, having won the June 16, 2026 Republican primary runoff. Before the state Senate, he served on the Forsyth County Planning Commission and worked in the Christian music industry, including eleven years as tour manager for musician Chris Tomlin, and as co-owner of Renewed Vision, a software company. He earned a bachelor's degree in business administration and communication studies from North Park University in 2001.$b$ where id = 51;  -- ballotpedia.org/Greg_Dolezal

update public.representatives set bio = $b$Josh McLaurin has represented Georgia State Senate District 14 (Sandy Springs area) since January 2023, having previously served two terms in the Georgia House of Representatives. He is an attorney whose career includes serving as acting general counsel for ExpressJet Airlines, as an associate at Krevolin & Horst LLC, and as a law clerk for the U.S. Court of Appeals for the Eleventh Circuit. McLaurin is the 2026 Democratic nominee for Lieutenant Governor of Georgia. He holds bachelor's and master's degrees from the University of Georgia and a J.D. from Yale Law School.$b$ where id = 38;  -- ballotpedia.org/Josh_McLaurin

update public.representatives set bio = $b$Brian Strickland served in the Georgia House of Representatives beginning in 2012 before being elected to Georgia State Senate District 42 (Henry, Newton, Walton, and Morgan counties) in 2018, where he chairs the Senate Judiciary Committee. He practices law at Smith, Welch, Webb & White in McDonough, Georgia, handling business litigation, real estate, and governmental matters. Strickland is the 2026 Republican nominee for Georgia Attorney General, having won the May 19, 2026 Republican primary. He holds a B.B.A. in economics from Valdosta State University and a J.D. from Florida Coastal School of Law.$b$ where id = 66;  -- ballotpedia.org/Brian_Strickland

update public.representatives set bio = $b$Caitlyn Gegen is the 2026 Democratic nominee for Georgia's 9th Congressional District, having grown up in the district. She has been involved in community organizing focused on criminal justice reform and women's rights. Gegen holds bachelor's and master's degrees from the University of Georgia and an additional master's degree from the London School of Economics.$b$ where id = 279;  -- ballotpedia.org/Georgia's_9th_Congressional_District_election,_2026

update public.representatives set bio = $b$Derek Dooley is an attorney and former college football head coach who was the 2026 Republican candidate for the U.S. Senate seat in Georgia, losing the June 16, 2026 runoff to Mike Collins. He served as head football coach at Louisiana Tech University (2007-2009) and the University of Tennessee (2010-2012), and practiced law at Nelson Mullins Riley & Scarborough in Atlanta prior to his coaching career. Dooley earned a bachelor's degree in government and foreign affairs from the University of Virginia in 1990 and a J.D. from the University of Georgia School of Law in 1994.$b$ where id = 280;  -- en.wikipedia.org/wiki/Derek_Dooley_(American_football)

-- Reynolds (SoS Dem nominee) — from the earlier sourcing pass; matched by name (id assigned at insert).
update public.representatives set bio = $b$Penny Brown Reynolds is the 2026 Democratic nominee for Georgia Secretary of State, having won the June 2026 Democratic primary runoff. She served as a Fulton County State Court judge and later as a civil-rights official at the U.S. Department of Agriculture during the Biden administration, and previously was executive counsel to Georgia Governor Roy Barnes. She is an ordained pastor and was known nationally for the television program "Family Court with Judge Penny."$b$ where name = 'Penny Brown Reynolds';  -- atlantanewsfirst.com / ballotready.org
