#!/usr/bin/env python3
"""Regenerate seeds/00_issues.sql from shared/issues.json (anti-drift, idempotent).

Source of truth is shared/issues.json. Run this after editing it, then apply the
seed (Supabase MCP / psql) so issues.json -> 00_issues.sql -> public.issues stay
in lockstep. Booleans default false; optional json keys: onboarding, needs_review,
perishable.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
issues = json.load(open(os.path.join(ROOT, 'shared', 'issues.json'), encoding='utf-8'))

def b(v):
    return 'true' if v else 'false'

def q(s):
    return "'" + s.replace("'", "''") + "'"

rows = []
for it in issues:
    rows.append("  ({}, {}, {}, {}, {}, {})".format(
        it['id'], q(it['text']), q(it['scope']),
        b(it.get('onboarding', False)),
        b(it.get('needs_review', False)),
        b(it.get('perishable', False)),
    ))

sql = """-- seeds/00_issues.sql
-- Canonical issue list. Source of truth: shared/issues.json.
-- GENERATED by scripts/gen_issues_seed.py — do not hand-edit; edit issues.json + regen.
-- Idempotent: ON CONFLICT (id) upserts text/scope/flags. Safe to re-run.

insert into public.issues (id, text, scope, onboarding, needs_review, perishable) values
""" + ",\n".join(rows) + """
on conflict (id) do update set
  text         = excluded.text,
  scope        = excluded.scope,
  onboarding   = excluded.onboarding,
  needs_review = excluded.needs_review,
  perishable   = excluded.perishable;
"""

out = os.path.join(ROOT, 'seeds', '00_issues.sql')
open(out, 'w', encoding='utf-8', newline='\n').write(sql)
print("wrote {} ({} issues; perishable={}, onboarding={}, needs_review={})".format(
    out, len(issues),
    sum(1 for i in issues if i.get('perishable')),
    sum(1 for i in issues if i.get('onboarding')),
    sum(1 for i in issues if i.get('needs_review')),
))
